name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x] #support latest two releases
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...